name: Gas report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache hardhat network fork
        uses: actions/cache@v2
        env:
          cache-name: cache-hardhat-network-fork
        with:
          path: cache/hardhat-network-fork
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('test/integration/fork-block-numbers.ts') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run gas tests
        run: yarn test:gas
        env:
          ETH_NODE_URI_MAINNET: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.ALCHEMY_API_KEY }}

      - name: Run eth gas reporter
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC }}
